(("Agatha Christie" . "agatha_christie.txt")
 ("Anne Rice" . "anne_rice.txt")
 ("Arthur Clarke" . "arthur_clarke.txt")
 ("Arthur Conan Doyle" . "arthur_conan_doyle.txt")
 ("Arthur Conan Doyle" . "arthur_conan_doyle_2.txt")
 ("Arthur Conan Doyle" . "arthur_conan_doyle_3.txt")
 ("Arthur Conan Doyle" . "arthur_conan_doyle_4.txt")
 ("Bram Stoker" . "bram_stoker.txt")
 ("Charles Dickens" . "charles_dickens.txt")
 ("Charles Dickens" . "charles_dickens_2.txt")
 ("Charles Dickens" . "charles_dickens_3.txt")
 ("Chuck Palahniuk" . "chuck_palahniuk.txt")
 ("Chuck Palahniuk" . "chuck_palahniuk_2.txt")
 ("Cory Doctorow" . "cory_doctorow.txt")
 ("Cory Doctorow" . "cory_doctorow_2.txt")
 ("Cory Doctorow" . "cory_doctorow_3.txt")
 ("Dan Brown" . "dan_brown.txt")
 ("Dan Brown" . "dan_brown_2.txt")
 ("Daniel Defoe" . "daniel_defoe.txt")
 ("Daniel Defoe" . "daniel_defoe_2.txt")
 ("David Foster Wallace" . "david_foster_wallace.txt")
 ("Douglas Adams" . "douglas_adams.txt")
 ("Edgar Allan Poe" . "edgar_allan_poe.txt")
 ("Edgar Allan Poe" . "edgar_allan_poe_2.txt")
 ("Ernest Hemingway" . "ernest_hemingway.txt")
 ("George Orwell" . "george_orwell.txt")
 ("George Orwell" . "george_orwell_2.txt")
 ("Gertrude Stein" . "gertrude_stein.txt")
 ("H. G. Wells" . "h_g_wells.txt")
 ("H. G. Wells" . "h_g_wells_2.txt")
 ("H. G. Wells" . "h_g_wells_3.txt")
 ("H. P. Lovecraft" . "h_p_lovecraft.txt")
 ("H. P. Lovecraft" . "h_p_lovecraft_2.txt")
 ("Harry Harrison" . "harry_harrison.txt")
 ("Harry Harrison" . "harry_harrison_2.txt")
 ("Ian Fleming" . "ian_fleming.txt")
 ("Ian Fleming" . "ian_fleming_2.txt")
 ("Isaac Asimov" . "isaac_asimov.txt")
 ("J. D. Salinger" . "j_d_salinger.txt")
 ("J. K. Rowling" . "j_k_rowling.txt")
 ("J. R. R. Tolkien" . "j_r_r_tolkien.txt")
 ("Jack London" . "jack_london.txt")
 ("Jack London" . "jack_london_2.txt")
 ("James Fenimore Cooper" . "james_fenimore_cooper.txt")
 ("James Fenimore Cooper" . "james_fenimore_cooper_2.txt")
 ("James Joyce" . "james_joyce.txt")
 ("Jane Austen" . "jane_austen.txt")
 ("Jane Austen" . "jane_austen_2.txt")
 ("Jonathan Swift" . "jonathan_swift.txt")
 ("Kurt Vonnegut" . "kurt_vonnegut.txt")
 ("Kurt Vonnegut" . "kurt_vonnegut_2.txt")
 ("Kurt Vonnegut" . "kurt_vonnegut_3.txt")
 ("L. Frank Baum" . "l_frank_baum.txt")
 ("Leo Tolstoy" . "leo_tolstoy.txt")
 ("Lewis Carroll" . "lewis_carroll.txt")
 ("Lewis Carroll" . "lewis_carroll_2.txt")
 ("Lewis Carroll" . "lewis_carroll_3.txt")
 ("Margaret Atwood" . "margaret_atwood.txt")
 ("Margaret Mitchell" . "margaret_mitchell.txt")
 ("Mario Puzo" . "mario_puzo.txt")
 ("Mark Twain" . "mark_twain.txt")
 ("Mark Twain" . "mark_twain_2.txt")
 ("Mary Shelley" . "mary_shelley.txt")
 ("Neil Gaiman" . "neil_gaiman.txt")
 ("Oscar Wilde" . "oscar_wilde.txt")
 ("Oscar Wilde" . "oscar_wilde_2.txt")
 ("P. G. Wodehouse" . "p_g_wodehouse.txt")
 ("P. G. Wodehouse" . "p_g_wodehouse_2.txt")
 ("Ray Bradbury" . "ray_bradbury.txt")
 ("Raymond Chandler" . "raymond_chandler.txt")
 ("Raymond Chandler" . "raymond_chandler_2.txt")
 ("Robert Louis Stevenson" . "robert_louis_stevenson.txt")
 ("Robert Louis Stevenson" . "robert_louis_stevenson_2.txt")
 ("Robert Louis Stevenson" . "robert_louis_stevenson_3.txt")
 ("Rudyard Kipling" . "rudyard_kipling.txt")
 ("Stephen King" . "stephen_king.txt")
 ("Stephen King" . "stephen_king_2.txt")
 ("Stephen King" . "stephen_king_3.txt")
 ("Stephenie Meyer" . "stephenie_meyer.txt")
 ("Ursula K. Le Guin" . "ursula_le_guin.txt")
 ("Ursula K. Le Guin" . "ursula_le_guin_2.txt")
 ("Vladimir Nabokov" . "vladimir_nabokov.txt")
 ("William Gibson" . "william_gibson.txt")
 ("William Shakespeare" . "william_shakespeare.txt")
 ("William Shakespeare" . "william_shakespeare_2.txt")
 ("William Shakespeare" . "william_shakespeare_3.txt")
 ("William Shakespeare" . "william_shakespeare_4.txt")
))
